version: "3"

services:
  app:
    volumes: &appvolumes
      - ${GITPOD_REPO_ROOT}:/var/www/html:cached

  phpfpm:
    volumes: *appvolumes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file: env/db.env
    ports:
      - "8080:80"
    depends_on:
      - db
